name: transition_easy
description: EasyTransition Simplify custom transition animations in Flutter. Create engaging page & dialog route transitions with ease
version: 1.0.8
homepage: https://github.com/georgesamirmansour/easyTransition

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.gsamir.transition_easy.transition_easy
        pluginClass: TransitionEasyPlugin
      ios:
        pluginClass: TransitionEasyPlugin
      linux:
        pluginClass: TransitionEasyPlugin
      macos:
        pluginClass: TransitionEasyPlugin
      windows:
        pluginClass: TransitionEasyPluginCApi
      web:
        pluginClass: TransitionEasyWeb
        fileName: transition_easy_web.dart


